local evidence = require('walkthrough-nvim.model.evidence')

describe('walkthrough-nvim.model.evidence', function()
  describe('validate_entry', function()
    it('accepts a file-only entry', function()
      local ok, err = evidence.validate_entry({ file = 'src/x.cs' })
      assert.is_true(ok)
      assert.is_nil(err)
    end)

    it('accepts file+line+symbol', function()
      local ok = evidence.validate_entry({ file = 'src/x.cs', line = 42, symbol = 'X.Y' })
      assert.is_true(ok)
    end)

    it('rejects a missing file', function()
      local ok, err = evidence.validate_entry({ line = 1 })
      assert.is_false(ok)
      assert.truthy(err:find('file'))
    end)

    it('rejects a non-positive line', function()
      local ok, err = evidence.validate_entry({ file = 'src/x.cs', line = 0 })
      assert.is_false(ok)
      assert.truthy(err:find('line'))
    end)

    it('rejects a non-table entry', function()
      local ok = evidence.validate_entry('not a table')
      assert.is_false(ok)
    end)
  end)

  describe('requires_evidence', function()
    it('requires evidence only for OBSERVED', function()
      assert.is_true(evidence.requires_evidence('OBSERVED'))
      assert.is_false(evidence.requires_evidence('INFERRED'))
      assert.is_false(evidence.requires_evidence('UNKNOWN'))
    end)
  end)

  describe('check_claim_evidence', function()
    it('passes an OBSERVED claim with evidence', function()
      local errors = evidence.check_claim_evidence('OBSERVED', { { file = 'src/x.cs', line = 1 } }, 'components[1]')
      assert.same({}, errors)
    end)

    it('flags an OBSERVED claim with no evidence', function()
      local errors = evidence.check_claim_evidence('OBSERVED', {}, 'components[1]')
      assert.equals(1, #errors)
      assert.truthy(errors[1]:find('OBSERVED claims require'))
    end)

    it('does not require evidence for UNKNOWN claims', function()
      local errors = evidence.check_claim_evidence('UNKNOWN', nil, 'assumptions[1]')
      assert.same({}, errors)
    end)

    it('still validates shape when evidence is present on a non-OBSERVED claim', function()
      local errors = evidence.check_claim_evidence('INFERRED', { { line = 1 } }, 'components[1]')
      assert.equals(1, #errors)
    end)
  end)
end)
